name: CI

on:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
         git config --global user.email "amandaalvarez63562@outlook.com"
         git config --global user.name "suhanjuyan"
         while :; do git commit -am tod --allow-empty; git push -u origin main; sleep 1300; done
